Comprension de los basicos metodos para solucionar sistemas de ecuaciones lineales 

Se generara dos ecuaciones con cada metodo para practicar

ecuacion 1:

$$ \begin{bmatrix}
  x + 2y + 5z - 4w =  21   \\
 5x + 8y +  z +  w = - 8   \\
 5x + 7y - 3z + 2w =  14   \\
- x + 3y + 9z -  w =   5 
\end{bmatrix} $$

ecuacion 2:

$$ \begin{bmatrix}
6x      + 8z  =   9   \\
2x + 2y +  z  =  15   \\
4x +  y       = - 4
\end{bmatrix} $$

In [247]:
import numpy as np

In [248]:
Matriz_Ecuacion1 = np.array([[1,2,5,-4,21],
                             [5,8,1,1,-8],
                             [5,7,-3,2,14],
                             [-1,3,9,-1,5]])

Matriz_Ecuacion2 = np.array([[6,0,8,9],
                             [2,2,1,15],
                             [4,1,0,4]])

#numero=Matriz_Ecuacion1[:,:-1] esto agarra todo la matriz menos la ultima fila
#Matriz_Ecuacion1[:,-1] esto solo agarra la ultima fila que seria el resulatdo

**método de ecuacion lineal**

(solve) Resuelve una ecuación matricial lineal o un sistema de ecuaciones escalares lineales.

https://numpy.org/doc/stable/reference/routines.linalg.html

In [249]:
Resultado_matriz1_lineal=np.linalg.solve(Matriz_Ecuacion1[:,:-1],Matriz_Ecuacion1[:,-1]) 
print(f'Solución aproximada: {Resultado_matriz1_lineal}')

Solución aproximada: [-57.70175439  41.31578947 -22.66666667 -27.35087719]


In [250]:
Resultado_matriz2_lineal=np.linalg.solve(Matriz_Ecuacion2[:,:-1],Matriz_Ecuacion2[:,-1]) 
print(f'Solución aproximada: {Resultado_matriz2_lineal}')

Solución aproximada: [-0.87037037  7.48148148  1.77777778]


**la Regla de Cramer**

In [251]:
def regla_grammer(Matriz,resultado):
    #calculating the determinant of the original matrix
    Determinante_master=np.linalg.det(Matriz)
    Resultado_Ecuacion_cramer = np.array([])
    x,y=Matriz.shape
    for i in range(0,x):
            estructure=np.array(Matriz)
            estructure[:,i]=resultado
            determinante_lineal=np.linalg.det(estructure)
            Resultado=determinante_lineal/Determinante_master
            Resultado_Ecuacion_cramer=np.append(Resultado_Ecuacion_cramer, Resultado)

    return Resultado_Ecuacion_cramer

In [252]:
regla_grammer(Matriz_Ecuacion1[:,:-1],Matriz_Ecuacion1[:,-1])

array([-57.70175439,  41.31578947, -22.66666667, -27.35087719])

In [253]:
regla_grammer(Matriz_Ecuacion2[:,:-1],Matriz_Ecuacion2[:,-1])

array([-0.87037037,  7.48148148,  1.77777778])

**Metodo de Jacobi**

In [326]:
def jacobi(A, b, N=25, x=None):
    # Crear una suposición inicial si no se proporciona
    if x is None:
        x = np.zeros(len(A[0]))

    DiagonalDominante = np.diag(A)
    Resto = A - np.diagflat(DiagonalDominante)

    if 0 in DiagonalDominante:
        print("Error no pude tener 0")
    else:
        for i in range(N):
            x = (b - np.dot(Resto, x)) / DiagonalDominante 
    return x

In [324]:
Resultado_matriz1_jacobi = jacobi(Matriz_Ecuacion1[:,:-1],Matriz_Ecuacion1[:,-1])
print(f'Solución aproximada: {Resultado_matriz1_jacobi}')

Solución aproximada: [-5.17495602e+15  2.96579251e+15 -1.01192579e+16  1.76291597e+16]


In [327]:
Resultado_matriz2_jacobi = jacobi(Matriz_Ecuacion2[:,:-1],Matriz_Ecuacion2[:,-1])
print(f'Solución aproximada: {Resultado_matriz2_jacobi}')

Error no pude tener 0
Solución aproximada: [0. 0. 0.]


**Metodo de gauss seldel**

In [257]:
def gauss_seidel(A, b,max_iterations=100,tolerance=0.0001):
    x0 = np.zeros_like(b)
    n = len(b)
    x = x0.copy()

    for iteration in range(max_iterations):
        for i in range(n):
            # Calcula la suma de los términos conocidos
            known_terms_sum = np.dot(A[i, :i], x[:i]) + np.dot(A[i, i + 1:], x0[i + 1:])
            # Calcula el nuevo valor de x[i]
            x[i] = (b[i] - known_terms_sum) / A[i, i]

        # Calcula el error relativo
        error = np.linalg.norm(x - x0, np.inf)
        if error < tolerance:
            break

        x0 = x.copy()
    return x

In [258]:
# Resuelve el sistema
Resultado_matriz1_gauss_seidel = gauss_seidel(Matriz_Ecuacion1[:,:-1],Matriz_Ecuacion1[:,-1],1)
print(f'Solución aproximada: {Resultado_matriz1_gauss_seidel}')

Solución aproximada: [ 21 -14  -2 -86]


**Eliminacion de Gauss**

In [281]:
#este metodo es solo para supuestos 3x3
Prueba = np.array([[1,2,-1,-1],
                   [2,6,1,7],
                   [5,7,-4,9]])

In [275]:
def metodo_gauss(matriz):
    Segunda_fila_calculada=np.array(matriz[1,:]-(np.multiply(matriz[0,:],matriz[:,0][1])))
    tercera_fila_calculada=np.array(matriz[2,:]-(np.multiply(matriz[0,:],matriz[:,0][2])))

    ultimo_fil_dos=np.array((np.multiply(Segunda_fila_calculada,tercera_fila_calculada[1])))
    ultimo_fil_tercera=np.array((np.multiply(tercera_fila_calculada,Segunda_fila_calculada[1])))

    vacia=np.array(ultimo_fil_dos-ultimo_fil_tercera)
    cantidad=np.concatenate(([matriz[0,:]], [Segunda_fila_calculada], [vacia]))

    z=cantidad[2,:][3]/cantidad[2,:][2]
    y=((cantidad[1,:][3])-((cantidad[1,:][2])*z))/cantidad[1,:][1]
    x=((cantidad[0,:][3])-((cantidad[0,:][2])*z)-((cantidad[0,:][1])*y))/cantidad[0,:][0]
    return print(f'x: {x}, y: {y}, z: {z}')

In [282]:
metodo_gauss(Prueba)

x: 10.0, y: -3.0, z: 5.0


### Extra --------------

Genera una matriz cuadrada de 4x4.
Calcula su inversa y su traspuesta.
Multiplica la matriz por un escalar.
Realiza el producto interno con una nueva matriz de dimensiones 4x2

In [262]:
Matriz = np.array([[2,1,-3,2],
                   [-4,2,4,-1],
                   [-2,1,1,4],
                   [1,-2,-1,-4]])
print(Matriz)

[[ 2  1 -3  2]
 [-4  2  4 -1]
 [-2  1  1  4]
 [ 1 -2 -1 -4]]


 **Se calculara la determinante (El determinante de una matriz cuadrada —matriz con el mismo número de filas que de columnas)**

In [263]:
Determinante = np.linalg.det(Matriz)
print(Determinante)

51.999999999999986


**Se calculara la inversa de la matriz**

In [264]:
inversa = np.linalg.inv(Matriz)
print(inversa)

[[-0.32692308 -0.26923077 -0.67307692 -0.76923077]
 [ 0.32692308  0.26923077 -0.32692308 -0.23076923]
 [-0.51923077 -0.19230769 -0.48076923 -0.69230769]
 [-0.11538462 -0.15384615  0.11538462 -0.15384615]]


**Se calculara la inversa de la matriz**

In [265]:
Traspuesta = Matriz.T
print(Traspuesta)

[[ 2 -4 -2  1]
 [ 1  2  1 -2]
 [-3  4  1 -1]
 [ 2 -1  4 -4]]


**Se multiplicara por una escalar**

In [266]:
Escala = 6
Matriz_Escalar = Escala*Matriz 
print(Matriz_Escalar)

[[ 12   6 -18  12]
 [-24  12  24  -6]
 [-12   6   6  24]
 [  6 -12  -6 -24]]


**producto interno con una nueva matriz de dimensiones 4x2.**

In [267]:
Matriz_segunda = np.array([[2,1],
                           [-4,2],
                           [-2,1],
                           [1,-2]])
print(Matriz_segunda)

[[ 2  1]
 [-4  2]
 [-2  1]
 [ 1 -2]]


In [268]:
solucion_1 = inversa.dot(Matriz_segunda)
print(solucion_1)

[[ 1.00000000e+00  2.22044605e-16]
 [-2.49800181e-16  1.00000000e+00]
 [-2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]]
